name: Pytest
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:
  push:
    branches:
      - master

jobs:
  update:
    os: ubuntu-latest
    python-version: 3.8
    steps:
      - name: Setup python
        uses: actions/setup-python@v2.3.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Checkout repo
        uses: actions/checkout@v2.4.0
      - name: test
        run: |
             python setup.py test
      - name: goodbye
        run: echo goodbye
